### ISSUE TITLE
Question about the in size of audio and video

### ISSUE THREAD

**Issue by flow-ljh** [WHULACC/DFERC#1]
Hello, thanks for your wonderful work, but  I have some questions about the inconsistency between in size of audio and audio_linear hidden_size. When I change it from 1582 to 100 as shown in pic, it works. So I am wondering whether it is correct to simply change the input size of audio.

![image](https://github.com/user-attachments/assets/a6020e50-7ecd-4d89-a1b9-9754de4aa146)

**Comment by unikcc** [comment]
Hi, we apologize for providing the incorrect dataset link. We have corrected the dataset URL in the README. You can use the updated dataset.

**Comment by flow-ljh** [comment]
Thanks for your reply, the problems have been solved.
